"use client";

import { Suspense, useCallback, useEffect, useMemo, useRef, useState } from "react";
import useSWR from "swr";
import { useRouter, useSearchParams } from "next/navigation";
import { apiGet } from "@/lib/api";
import { useJobs } from "@/hooks/use-jobs";
import type { Job, Resume } from "@/types";
import {
  ArrowLeft,
  Briefcase,
  Loader2,
  RotateCcw,
  Send,
  Sparkles,
  StopCircle,
  User,
} from "lucide-react";
import { toast } from "sonner";

/**
 * /interviews/practice — live, in-character interview practice with Claude.
 *
 * Two-phase UX:
 *   1. Setup: pick a saved job (or paste a JD), confirm resume, click Start.
 *   2. Chat: turn-taking with the AI interviewer. Feedback is rendered
 *      inline as part of each assistant turn.
 *
 * State is kept entirely client-side — we don't persist transcripts yet.
 * The "Start over" button resets without leaving the page; "End & debrief"
 * sends a magic `end` message that the system prompt recognizes as the
 * cue to produce a summary.
 */

type ChatMessage = {
  role: "user" | "assistant";
  content: string;
  ts: number;
};

type Phase = "setup" | "chat";

export default function InterviewPracticePage() {
  // Wrap the content in Suspense so useSearchParams doesn't bail out
  // of prerender during `next build`.
  return (
    <Suspense fallback={null}>
      <InterviewPracticeContent />
    </Suspense>
  );
}

function InterviewPracticeContent() {
  const router = useRouter();
  const searchParams = useSearchParams();

  const { jobs } = useJobs();
  const { data: resumes } = useSWR<Resume[]>(
    "/resumes",
    () => apiGet<Resume[]>("/resumes"),
    { revalidateOnFocus: false }
  );
  const primaryResume = resumes?.find((r) => r.is_primary) ?? resumes?.[0];

  const initialJobId = searchParams?.get("jobId") ?? "";
  const [jobId, setJobId] = useState(initialJobId);
  const [customJD, setCustomJD] = useState("");
  const [customTitle, setCustomTitle] = useState("");
  const [customCompany, setCustomCompany] = useState("");
  const [phase, setPhase] = useState<Phase>("setup");

  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [pending, setPending] = useState(false);
  const [draft, setDraft] = useState("");
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const inputRef = useRef<HTMLTextAreaElement | null>(null);

  // If the page opens with ?jobId=X, auto-kick to the chat phase once
  // jobs have loaded — saves the user a click.
  const autoStartedRef = useRef(false);
  useEffect(() => {
    if (
      !autoStartedRef.current &&
      initialJobId &&
      jobs.find((j) => j.id === initialJobId)
    ) {
      autoStartedRef.current = true;
      start();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [jobs, initialJobId]);

  // Scroll the transcript to the bottom when new messages arrive.
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, pending]);

  // Resolve the active job context (saved job OR pasted JD fallback).
  const activeContext = useMemo(() => {
    const job = jobs.find((j) => j.id === jobId);
    if (job) {
      return {
        job_title: job.title,
        company: job.company,
        job_description: job.description ?? "",
      };
    }
    return {
      job_title: customTitle || "the role",
      company: customCompany || "the company",
      job_description: customJD,
    };
  }, [jobId, jobs, customTitle, customCompany, customJD]);

  const canStart = Boolean(
    jobId || (customTitle.trim() && customCompany.trim())
  );

  const start = useCallback(async () => {
    setPending(true);
    setMessages([]);
    setPhase("chat");
    // The first turn is generated by sending a "system kickoff" user
    // message — Anthropic's API requires at least one user message.
    // The opener phrasing doesn't appear to the candidate.
    const kickoff: ChatMessage = {
      role: "user",
      content: "Let's begin.",
      ts: Date.now(),
    };
    try {
      const res = await fetch("/api/ai/interview-practice", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: [{ role: "user", content: kickoff.content }],
          ...activeContext,
          resume_text: primaryResume?.parsed_text ?? "",
        }),
      });
      if (!res.ok) throw new Error(`${res.status}`);
      const data = (await res.json()) as { reply?: string; error?: string };
      if (data.error) throw new Error(data.error);
      setMessages([
        kickoff,
        { role: "assistant", content: data.reply ?? "(no reply)", ts: Date.now() },
      ]);
      setTimeout(() => inputRef.current?.focus(), 50);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to start");
      setPhase("setup");
    } finally {
      setPending(false);
    }
  }, [activeContext, primaryResume]);

  const send = useCallback(
    async (text: string) => {
      if (!text.trim() || pending) return;
      const next: ChatMessage = { role: "user", content: text.trim(), ts: Date.now() };
      const nextMessages = [...messages, next];
      setMessages(nextMessages);
      setDraft("");
      setPending(true);
      try {
        const res = await fetch("/api/ai/interview-practice", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            messages: nextMessages.map((m) => ({ role: m.role, content: m.content })),
            ...activeContext,
            resume_text: primaryResume?.parsed_text ?? "",
          }),
        });
        if (!res.ok) throw new Error(`${res.status}`);
        const data = (await res.json()) as { reply?: string; error?: string };
        if (data.error) throw new Error(data.error);
        setMessages((prev) => [
          ...prev,
          { role: "assistant", content: data.reply ?? "(no reply)", ts: Date.now() },
        ]);
      } catch (err) {
        toast.error(err instanceof Error ? err.message : "Network error");
      } finally {
        setPending(false);
      }
    },
    [messages, activeContext, primaryResume, pending]
  );

  const onKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      void send(draft);
    }
  };

  const endSession = useCallback(() => {
    if (pending) return;
    void send("end");
  }, [send, pending]);

  const reset = useCallback(() => {
    setMessages([]);
    setDraft("");
    setPhase("setup");
    autoStartedRef.current = false;
  }, []);

  // ── Setup phase ──────────────────────────────────────────────────
  if (phase === "setup") {
    return (
      <div>
        <button
          type="button"
          onClick={() => router.push("/interviews")}
          className="inline-flex items-center gap-1 text-xs text-zinc-500 hover:text-zinc-200 mb-4"
        >
          <ArrowLeft className="h-3 w-3" />
          Back to Interview Prep
        </button>

        <div className="mb-5">
          <div className="inline-flex items-center gap-2 rounded-full border border-violet-500/30 bg-violet-500/10 px-3 py-1 text-xs text-violet-200 mb-3">
            <Sparkles className="h-3 w-3" />
            New — AI practice sessions
          </div>
          <h1 className="text-2xl font-bold text-white tracking-tight">
            Practice interview
          </h1>
          <p className="text-sm text-zinc-400 mt-1 max-w-xl leading-relaxed">
            Pick a role and we&apos;ll play the hiring manager — warm-up
            question, follow-ups, inline feedback after each answer, then a
            short debrief when you&apos;re done.
          </p>
        </div>

        <div className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-5 space-y-5 max-w-2xl">
          <div>
            <label className="block text-xs font-semibold text-zinc-400 uppercase tracking-widest mb-2">
              Use a saved job
            </label>
            {jobs.length > 0 ? (
              <select
                value={jobId}
                onChange={(e) => setJobId(e.target.value)}
                className="w-full rounded-md bg-zinc-800 border border-zinc-700 text-sm text-white px-3 py-2"
              >
                <option value="">— Pick a role —</option>
                {jobs.map((j: Job) => (
                  <option key={j.id} value={j.id}>
                    {j.title} · {j.company}
                  </option>
                ))}
              </select>
            ) : (
              <p className="text-xs text-zinc-500">
                No saved roles yet. Add one on the Dashboard, or paste the
                details below.
              </p>
            )}
          </div>

          {!jobId && (
            <div className="border-t border-zinc-800 pt-5 space-y-3">
              <label className="block text-xs font-semibold text-zinc-400 uppercase tracking-widest">
                Or describe a role manually
              </label>
              <div className="grid grid-cols-2 gap-3">
                <input
                  type="text"
                  value={customTitle}
                  onChange={(e) => setCustomTitle(e.target.value)}
                  placeholder="Job title"
                  className="rounded-md bg-zinc-800 border border-zinc-700 text-sm text-white px-3 py-2 placeholder:text-zinc-500"
                />
                <input
                  type="text"
                  value={customCompany}
                  onChange={(e) => setCustomCompany(e.target.value)}
                  placeholder="Company"
                  className="rounded-md bg-zinc-800 border border-zinc-700 text-sm text-white px-3 py-2 placeholder:text-zinc-500"
                />
              </div>
              <textarea
                value={customJD}
                onChange={(e) => setCustomJD(e.target.value)}
                rows={5}
                placeholder="Paste the job description (optional but improves question quality)"
                className="w-full rounded-md bg-zinc-800 border border-zinc-700 text-sm text-white px-3 py-2 placeholder:text-zinc-500 resize-y"
              />
            </div>
          )}

          <div className="border-t border-zinc-800 pt-4 flex items-center justify-between gap-2">
            <div className="text-xs text-zinc-500">
              {primaryResume
                ? `Using primary resume: ${primaryResume.file_name}`
                : "No resume uploaded — feedback will be generic."}
            </div>
            <button
              type="button"
              disabled={!canStart || pending}
              onClick={() => void start()}
              className="inline-flex items-center gap-2 rounded-lg bg-blue-600 hover:bg-blue-700 disabled:bg-zinc-700 disabled:cursor-not-allowed px-4 py-2 text-sm font-medium text-white shadow-lg shadow-blue-600/20"
            >
              {pending ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Starting…
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4" />
                  Start practice
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ── Chat phase ───────────────────────────────────────────────────
  return (
    <div className="flex flex-col h-[calc(100vh-8rem)]">
      <div className="flex items-center justify-between mb-3 gap-2">
        <div className="min-w-0">
          <div className="flex items-center gap-2 text-xs text-zinc-500">
            <Briefcase className="h-3 w-3" />
            <span className="truncate">
              Practicing: {activeContext.job_title} · {activeContext.company}
            </span>
          </div>
          <h1 className="text-lg font-semibold text-white truncate">
            Mock interview
          </h1>
        </div>
        <div className="flex items-center gap-1">
          <button
            type="button"
            onClick={reset}
            className="inline-flex items-center gap-1 rounded-md border border-zinc-700 bg-zinc-900 px-2.5 py-1.5 text-xs text-zinc-200 hover:bg-zinc-800"
          >
            <RotateCcw className="h-3 w-3" />
            New session
          </button>
          <button
            type="button"
            onClick={endSession}
            disabled={pending}
            className="inline-flex items-center gap-1 rounded-md border border-amber-500/40 bg-amber-500/10 px-2.5 py-1.5 text-xs text-amber-200 hover:bg-amber-500/20 disabled:opacity-50"
          >
            <StopCircle className="h-3 w-3" />
            End &amp; debrief
          </button>
        </div>
      </div>

      <div
        ref={scrollRef}
        className="flex-1 overflow-y-auto rounded-xl border border-zinc-800 bg-zinc-950/60 p-4 space-y-4"
      >
        {messages
          // Hide the synthetic "Let's begin." kickoff so the user sees a
          // clean transcript that starts with the interviewer.
          .filter((m, i) => !(i === 0 && m.role === "user" && m.content === "Let's begin."))
          .map((m, i) => (
            <MessageBubble key={i} message={m} />
          ))}
        {pending && (
          <div className="flex items-center gap-2 text-xs text-zinc-500 pl-11">
            <Loader2 className="h-3 w-3 animate-spin" />
            Interviewer is typing…
          </div>
        )}
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault();
          void send(draft);
        }}
        className="mt-3 flex items-end gap-2 rounded-xl border border-zinc-800 bg-zinc-900/60 p-2"
      >
        <textarea
          ref={inputRef}
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={onKeyDown}
          rows={2}
          placeholder="Type your answer… (Enter to send, Shift+Enter for a new line)"
          className="flex-1 bg-transparent text-sm text-white placeholder:text-zinc-500 resize-none focus:outline-none px-2 py-1.5"
          disabled={pending}
        />
        <button
          type="submit"
          disabled={!draft.trim() || pending}
          className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 disabled:bg-zinc-700 disabled:cursor-not-allowed px-3 py-2 text-sm font-medium text-white"
        >
          <Send className="h-3.5 w-3.5" />
          Send
        </button>
      </form>
    </div>
  );
}

function MessageBubble({ message }: { message: ChatMessage }) {
  const isUser = message.role === "user";
  return (
    <div className={`flex gap-3 ${isUser ? "flex-row-reverse" : ""}`}>
      <div
        className={`h-8 w-8 shrink-0 rounded-full flex items-center justify-center ${
          isUser
            ? "bg-blue-600/20 text-blue-300 border border-blue-500/30"
            : "bg-violet-600/20 text-violet-300 border border-violet-500/30"
        }`}
        aria-hidden
      >
        {isUser ? <User className="h-4 w-4" /> : <Sparkles className="h-4 w-4" />}
      </div>
      <div
        className={`max-w-[80%] rounded-2xl px-4 py-2.5 text-sm leading-relaxed whitespace-pre-wrap ${
          isUser
            ? "bg-blue-600 text-white rounded-tr-sm"
            : "bg-zinc-800 text-zinc-100 border border-zinc-700 rounded-tl-sm"
        }`}
      >
        {message.content}
      </div>
    </div>
  );
}
